name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Tidy Go modules
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

  govulncheck:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install latest govulncheck from source
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Preload module dependencies
        run: go mod download

      - name: Run govulncheck
        run: govulncheck ./...

  build:
    name: Build Binary
    runs-on: ubuntu-latest
    needs: [test, govulncheck]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Tidy Go modules
        run: go mod tidy

      - name: Build
        run: go build -v ./...

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
